# Presentation of the Work {.unnumbered}

This page serves as a platform to view the Maps for the final MSc dissertation project, titled: Delineation of perceptual Neighbourhoods in the housing market - Geo-text location modelling through Classification and Unsupervised Clustering.

1.  The First Page provides the prototype output for the Greater London Map proposition, which leverages Zero-Shot encoding constructed through the BART pre-trained models. We construct the boundaries through KDE (Kernel Density Estimates) area prediction, and then pair these with geo-demographically granular pre-constructed areas, in this case, Lower Super-Output Areas (LSOA) provided in the 2021 UK Census.

2.  The second map output provides the boundaries created through Zero-shot encoding but uses Output Areas (OAs) instead of LSOAs.

3.  The Third illustrates results from Unsupervised Topic Modelling where we let the algorithm directly recognise trends in the data to make up clusters of areas, we serve as potential basis for neighbourhood delineation proposals.

4.  The Fourth adds a geo-demographic dimension to the analysis of the unsupervised clusters. We add a dispersion of LSOA with colours based on their deprivation decile and we see general trends in our clusters where less detail is available in more deprived areas. Decile 1 means the LSOA is in the 10% lowest most deprived area in the UK, decile 2 meaning in the bottom 20% and so on

5.  The fifth illustrate KDE Zero-shot historical examples, with data from 2015 with the wish to show the evolution of these areas over time. This is a work in progress but aims to illustrate the temporal importance when defining a neighbourhood. We have additional results since 1995 that can really support this evolution

6.  The Final map is our attempt using Name entity recognition for completely unsupervised boundary delineation. Certain areas are accurate, but many area are incorrect or do not refer to actual potential neighbourhoods useful for the housing market (i.e., east London, River Thames etc.). Although interesting to illustrate the potential of this method, we do not develop it further
